# SPDX-FileCopyrightText: 2021-2022 SanderTheDragon <sanderthedragon@zoho.com>
#
# SPDX-License-Identifier: CC0-1.0

image: registry.gitlab.com/sanderthedragon/scppl:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mkdir $CI_PROJECT_DIR/build
    - cd $CI_PROJECT_DIR/build
    - cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DSCPPL_LIBRARY_BINARY=ON -DSCPPL_LIBRARY_OS=ON -DSCPPL_TOOL_CLANG_TIDY=OFF -DSCPPL_TOOL_IWYU=OFF -DSCPPL_BUILD_DOCS=ON -DSCPPL_BUILD_TESTS=ON -DSCPPL_BUILD_COVERAGE=ON
    - make
  artifacts:
    paths:
      - "$CI_PROJECT_DIR/build"

# Download the latest artifacts instead of rebuilding
download:
  stage: build
  script:
    - cd $CI_PROJECT_DIR
    - curl -L -o build.zip "https://gitlab.com/$CI_MERGE_REQUEST_PROJECT_PATH/-/jobs/artifacts/$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME/download?job=build"
    - unzip build.zip
  artifacts:
    paths:
      - "$CI_PROJECT_DIR/build"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

unit-test:
  stage: test
  needs:
    - job: build
      artifacts: true
  script:
    - cd $CI_PROJECT_DIR/build
    - ctest --output-junit $CI_PROJECT_DIR/report.xml
  artifacts:
    reports:
      junit: "report.xml"
    paths:
      - "$CI_PROJECT_DIR/build"

coverage:
  stage: test
  needs:
    - job: unit-test
      artifacts: true
  script:
    - cd $CI_PROJECT_DIR/build
    - gcovr -r $CI_PROJECT_DIR -x $CI_PROJECT_DIR/coverage.xml --exclude-lines-by-pattern "(\s+throw .+)|(.*GCOVR_EXCL_LINE.*)" --exclude-throw-branches --print-summary
  coverage: '/lines: \d+\.\d+%/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: "coverage.xml"

clang-tidy:
  stage: test
  needs:
    - job: download
      artifacts: true
  script:
    - cd $CI_PROJECT_DIR
    - run-clang-tidy-14 -quiet -p $CI_PROJECT_DIR/build
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: manual
      allow_failure: true

iwyu:
  stage: test
  needs:
    - job: download
      artifacts: true
  script:
    - cd $CI_PROJECT_DIR
    - iwyu_tool -o clang -p $CI_PROJECT_DIR/build -- -Xiwyu --mapping_file=$CI_PROJECT_DIR/cmake/tools/googletest.imp -I/usr/lib/clang/14/include
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: manual
      allow_failure: true

memory:
  stage: test
  needs:
    - job: download
      artifacts: true
  script:
    - cd $CI_PROJECT_DIR/build
    - valgrind --leak-check=full --show-leak-kinds=all -s ctest
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

reuse:
  stage: test
  needs: []
  script:
    - cd $CI_PROJECT_DIR
    - reuse lint
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

pages:
  stage: deploy
  needs:
    - job: build
      artifacts: true
  script:
    - cd $CI_PROJECT_DIR/build
    - make Documentation BinaryDocumentation OSDocumentation
    - cp -R documentation/public $CI_PROJECT_DIR
  artifacts:
    paths:
      - "public"
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
