# SPDX-FileCopyrightText: 2021-2022 SanderTheDragon <sanderthedragon@zoho.com>
#
# SPDX-License-Identifier: CC0-1.0

image: registry.gitlab.com/sanderthedragon/scppl:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mkdir $CI_PROJECT_DIR/build
    - cd $CI_PROJECT_DIR/build
    - cmake .. -DSCPPL_LIBRARY_BINARY=ON -DSCPPL_TOOL_CLANG_TIDY=OFF -DSCPPL_TOOL_IWYU=OFF -DSCPPL_BUILD_DOCS=ON -DSCPPL_BUILD_TESTS=ON -DSCPPL_BUILD_COVERAGE=ON
    - make
  artifacts:
    paths:
      - "$CI_PROJECT_DIR/build"

unit-test:
  stage: test
  dependencies:
    - "build"
  script:
    - cd $CI_PROJECT_DIR/build
    - ctest --output-junit $CI_PROJECT_DIR/report.xml
  artifacts:
    reports:
      junit: "report.xml"

coverage:
  stage: test
  dependencies:
    - "build"
  script:
    - pip3 install gcovr
    - cd $CI_PROJECT_DIR/build
    - ctest
    - gcovr -r $CI_PROJECT_DIR -x $CI_PROJECT_DIR/coverage.xml --exclude-lines-by-pattern "\s+throw .+" --exclude-throw-branches --print-summary
  coverage: '/lines: \d+\.\d+%/'
  artifacts:
    reports:
      cobertura: "coverage.xml"

pages:
  stage: deploy
  dependencies:
    - "build"
  before_script:
    - pip install -r $CI_PROJECT_DIR/requirements.txt
  script:
    - cd $CI_PROJECT_DIR/build
    - make Documentation BinaryDocumentation
    - cp -R documentation/public $CI_PROJECT_DIR
  artifacts:
    paths:
      - "public"
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
